language: node_js
node_js:
  - "0.10"

env:
  global:
    - secure: "CFH6k4N0JIjJ17qKdKDqjX45yOTcB6DY8wAHL/lDHneaIHeg0A6waHA1Ri6jjChiwsw7h8tSSYmqu+x2fdLNI4SxpVapcRhr8iunoWOIypHDJ0J8cpn4py3zs70g+RkRLXE++Prys/zj2AEvXftBQDlb0dRWf751y+TNFudC0vA="
    - secure: "RNrtdx+CQecGkBWsaWGEr3IEsQsjXpVL/+lJfRnZYs5jQP7uE9sjWLZsBQsEGC9lFinmY+HoU0ucfxA9Kqe1Ts6itEP2lTPg2le/xRZRV6g0jCcvqc57l7WwIxhxQR74u2J3n+NhVT4FE7tvLx4jhkoCP0nIokOfsZF7+EY9W4k="

addons:
  sauce_connect: true

install:
  - npm install
  - npm install protractor cucumber bower -g
  - npm install lodash
  - bower install

script:
  - node test/scripts/web-server.js &
  - sleep 1 # give the server some time to get his things... drink coffee.. and such
  - protractor
