language: node_js
node_js:
  - "0.10"

env:
  global:
    - secure: nNjYM73ECnxTS5E4Tqp2hgfQqa+J5elCxGmlJXvSHHLYDr12/BiSFCaGoOSBtVUl4YByaaOpDDtT+9EHsZLrDnhAiisqWw8l7zPcsOoHFLKxD49HJaAw47j0YPBgJ2k1z4SThrTyCa3+sBxcqjrrz0pcKZ7rooPgljHGAvtHkaY=
    - secure: TV53LPRKV622p0fGIuMwoLQCbXo4PvNIbKt4yCRLaIZT3QvOWSPx3hIghgEyq85TdGfy8tr2aPvHfBWr9ozIFDcclDvxVc/t3n4E+rG9e+9Cb235JtwDbWppJPj1OTSH/af+oyWuKK+IPTtgNVTcvyj24GGy9IsH52ngJEqbgBc=

addons:
  sauce_connect: true

install:
  - npm install
  - npm install protractor cucumber bower -g
  - npm install lodash
  - bower install

script:
  - node test/scripts/web-server.js &
  - sleep 1 # give the server some time to get his things... drink coffee.. and such
  - protractor ./test/travis.conf.js